### ISSUE TITLE
Post middleware causes response to hang for large page sizes

### ISSUE THREAD

**Issue by hrc-yu** [merge-api/merge-sdk-typescript#19]
**Issue**: 

When making a request with a larger page size (for the data set I'm testing with, anything above `pageSize: 38`), the SDK request hangs if a post middleware is set. It does not seem to matter what is happening in the middleware - just a log statement causes this problem. 

The request completes as expected if the page size is set lower. It also completes for a larger page size (up to the API's limit of 100) if no middleware is set.

I am wondering if it's an issue with the use of `response.clone()` [here](https://github.com/merge-api/merge-sdk-typescript/blob/main/src/runtime.ts#L97). I see a potentially related open issue for [node-fetch](https://github.com/node-fetch/node-fetch/issues/1131) here.

Let me know if you have any suggestions on how to resolve this, or if I can provide more information! 

**Sample code**: 
```javascript
import { Configuration, HRIS } from "@mergeapi/merge-sdk-typescript";
import fetch from "node-fetch";

const post = async () => {
  console.log("post middleware");
};

const apiConfig = new Configuration({
  accessToken: "<redacted>",
  apiKey: "<redacted>",
  basePath: "https://api-eu.merge.dev/api",
  fetchApi: fetch,
  middleware: [{ post }],
});

const api = new HRIS.EmployeesApi(apiConfig);
const response = await api.employeesList({ pageSize: 39 });
```

**Version info:**
```json
"@mergeapi/merge-sdk-typescript": "2.0.2"
"node-fetch": "2.6.7"
"node": ">=14.16.1"
```

**Comment by leewang0** [comment]
This was fixed in 3.0.2
