### ISSUE TITLE
Marketing support?

### ISSUE THREAD

**Issue by dobrynin** [merge-api/merge-sdk-typescript#32]
Am I correct in understanding that this library does not yet support Marketing Automation? If so, is there a timeline for when support will be added? Thanks!

**Comment by kevinmerge** [comment]
Thanks for letting us know, the team is working on getting this added by EoW!

**Comment by dobrynin** [comment]
Awesome, thanks! I also tried to hack the library to support the Merge Link flow but I got an error w/ a bad request, so I resorted to trying out the link flow using the (older?) HRIS npm module. Seemed a little strange to use that because we are interested in the CRM + Marketing platforms, but it worked.

**Comment by leewang0** [comment]
We added marketing automation to this SDK in version `3.0.6`, thanks for the request.
